import { useState } from "react";
import { useQuery,useMutation,useQueryClient } from "@tanstack/react-query";
import { apiClient } from "../api/client";
import { ErrorState } from "./ErrorState";
import { LoadingState } from "./LoadingState";
import { Icon } from "./Icon";
import "../workspace.css";
export type RubricCriterion={id:string;label:string;maxPoints:number;description:string};
export type RubricMark={id:string;label:string;maxPoints:number;points:number;feedback:string|null};
export type RubricDocument={version:number;maxScore:number;locked:boolean;criteria:RubricCriterion[]};
export function useRubric(assignmentId:number,student=false){return useQuery({queryKey:[student?"student":"admin","rubric",assignmentId],queryFn:async()=>(await apiClient.get<RubricDocument>(`/api/${student?"student":"admin"}/assignments/${assignmentId}/rubric`)).data});}
export function RubricBreakdown({marks}:{marks:RubricMark[]}){if(!marks.length)return null;return <section className="rubric-breakdown" aria-label="Score breakdown"><h4>How your work was scored</h4>{marks.map(mark=><article key={mark.id}><div><strong>{mark.label}</strong><span>{mark.points} / {mark.maxPoints}</span></div>{mark.feedback&&<p>{mark.feedback}</p>}</article>)}</section>;}
export function StudentRubric({assignmentId}:{assignmentId:number}){const q=useRubric(assignmentId,true);if(q.isError)return <ErrorState message="Could not load the scoring criteria." onRetry={()=>q.refetch()}/>;if(!q.data?.criteria.length)return null;return <details className="rubric-breakdown"><summary>What your instructor will look for · {q.data.maxScore} points</summary>{q.data.criteria.map(c=><article key={c.id}><div><strong>{c.label}</strong><span>{c.maxPoints} points</span></div><p>{c.description}</p></article>)}</details>;}
function Editor({assignmentId,document}:{assignmentId:number;document:RubricDocument}){
 const [criteria,setCriteria]=useState(document.criteria);const cache=useQueryClient();
 const save=useMutation({meta:{notify:true},mutationFn:async()=>apiClient.put(`/api/admin/assignments/${assignmentId}/rubric`,{version:document.version,criteria}),onSuccess:()=>cache.invalidateQueries({queryKey:["admin","rubric",assignmentId]})});
 const total=criteria.reduce((sum,c)=>sum+c.maxPoints,0);const locked=document.locked||save.isPending;
 const edit=(id:string,patch:Partial<RubricCriterion>)=>setCriteria(rows=>rows.map(c=>c.id===id?{...c,...patch}:c));
 const valid=(criteria.length===0||total===document.maxScore)&&criteria.every(c=>c.label.trim()&&Number.isInteger(c.maxPoints)&&c.maxPoints>0);
 return <section className="card rubric-editor" style={{padding:24,marginTop:24}}><span className="eyebrow">CONSISTENT GRADING</span><h3>Score by criterion</h3><p className="text-muted">Break the {document.maxScore}-point assignment into clear criteria. Students can see these before submitting.</p>{document.locked&&<p className="notice-panel">Criteria are locked because submissions have started. Saved reviews keep their original score breakdown.</p>}
 <div className="rubric-criteria">{criteria.map((c,index)=><article className="rubric-criterion" key={c.id}><div className="rubric-criterion__heading"><strong>Criterion {index+1}</strong><button type="button" className="icon-btn" disabled={locked} aria-label={`Remove criterion ${index+1}`} onClick={()=>setCriteria(rows=>rows.filter(row=>row.id!==c.id))}><Icon name="trash" size={16}/></button></div><div className="admin-form-grid"><label className="form-field">Name<input maxLength={160} value={c.label} disabled={locked} onChange={e=>edit(c.id,{label:e.target.value})}/></label><label className="form-field">Maximum points<input type="number" min={1} max={1000} value={c.maxPoints} disabled={locked} onChange={e=>edit(c.id,{maxPoints:Number(e.target.value)})}/></label><label className="form-field form-field--full">What good work looks like<textarea rows={2} maxLength={2000} value={c.description} disabled={locked} onChange={e=>edit(c.id,{description:e.target.value})}/></label></div></article>)}</div>
 {!document.locked&&<><div className="admin-actions-row"><button type="button" className="btn btn-secondary" disabled={locked||criteria.length>=20} onClick={()=>setCriteria(rows=>[...rows,{id:crypto.randomUUID(),label:"",description:"",maxPoints:Math.max(1,document.maxScore-total)}])}><Icon name="plus" size={16}/>Add criterion</button><span className="rubric-points">{total} / {document.maxScore}</span></div>{criteria.length>0&&total!==document.maxScore&&<p role="status">Adjust the points to total {document.maxScore} before saving.</p>}<button type="button" className="btn btn-primary" style={{marginTop:16}} disabled={locked||!valid} onClick={()=>save.mutate()}>{save.isPending?"Saving criteria…":"Save scoring criteria"}</button></>}
 {criteria.length===0&&document.locked&&<p className="text-muted">This assignment uses a single overall score.</p>}</section>;
}
export function AdminRubricEditor({assignmentId}:{assignmentId:number}){const q=useRubric(assignmentId);if(q.isLoading)return <LoadingState label="Loading scoring criteria…"/>;if(!q.data)return <ErrorState message="Could not load scoring criteria." onRetry={()=>q.refetch()}/>;return <Editor key={`${q.data.version}-${q.data.maxScore}`} assignmentId={assignmentId} document={q.data}/>;}
