import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { apiClient } from "../api/client";
import { formatDateTime } from "../utils/formatDate";
import { ErrorState } from "./ErrorState";
type Overview={progress:{overallPercentage:number;courseComplete:boolean;classesCompleted:number;classesTotal:number;quizzesPassed:number;quizzesTotal:number;assignmentsSubmitted:number;assignmentsReviewed:number;assignmentsTotal:number};upcoming:{id:number;title:string;scheduledAt:string}[];assignments:{classId:number;title:string;dueAt:string|null;status:string;score:number|null}[];quizResults:{attemptId:number;classTitle:string;submittedAt:string;percentage:number;passed:boolean}[];attendance:{classId:number;title:string;status:string}[]};
export function LearningOverview({courseId,cohortId}:{courseId:number;cohortId?:number}){const q=useQuery({queryKey:["student","courses",courseId,"overview",cohortId],queryFn:async()=>(await apiClient.get<Overview>(`/api/student/courses/${courseId}/overview`,{params:{cohortId}})).data});
 if(q.isError)return <ErrorState message="Could not load your learning overview." onRetry={()=>q.refetch()}/>;if(!q.data)return <p className="text-muted">Loading your learning overview…</p>;const o=q.data,p=o.progress;
 return <section aria-label="Learning overview"><div className="learning-metrics">{[["Lessons completed",p.classesCompleted,p.classesTotal],["Quizzes passed",p.quizzesPassed,p.quizzesTotal],["Assignments reviewed",p.assignmentsReviewed,p.assignmentsTotal]].map(([title,count,total])=><div className="card" key={title}><span>{title}</span><strong>{count}<small> / {total}</small></strong></div>)}</div><p className="text-muted">{p.courseComplete?"Completion requirements met.":`${p.overallPercentage}% activity progress. Completion may still require grading or attendance.`}</p>
 <div className="learning-overview-grid"><section className="card student-class-card"><h3>Coming up</h3>{o.upcoming.length===0?<p className="text-muted">No upcoming class scheduled.</p>:o.upcoming.map(s=><p key={s.id}><Link to={`/student/classes/${s.id}`}>{s.title}</Link><small style={{display:"block"}}>{formatDateTime(s.scheduledAt)}</small></p>)}</section><section className="card student-class-card"><h3>Your assignments</h3>{o.assignments.length===0?<p className="text-muted">No assignments yet.</p>:o.assignments.map(a=><p key={a.classId}><Link to={`/student/classes/${a.classId}`}>{a.title}</Link><small style={{display:"block"}}>{a.status.replaceAll("_"," ")}{a.score!==null?` · ${a.score} points`:""}{a.dueAt?` · Due ${formatDateTime(a.dueAt)}`:""}</small></p>)}</section></div>
 <details className="card student-class-card"><summary>Quiz results ({o.quizResults.length})</summary>{o.quizResults.map(r=><p key={r.attemptId}><Link to={`/student/quiz-results/${r.attemptId}`}>{r.classTitle} · {Math.round(r.percentage)}% · {r.passed?"Passed":"Not passed"}</Link><small style={{display:"block"}}>{formatDateTime(r.submittedAt)}</small></p>)}</details>
 <details className="card student-class-card"><summary>Attendance ({o.attendance.length} classes)</summary>{o.attendance.map(a=><p key={a.classId}>{a.title}<strong style={{display:"block"}}>{a.status.toLowerCase()}</strong></p>)}</details></section>;}
