import { useEffect, useState, type FormEvent } from 'react';
import { useAdminSiteContent, useSaveSiteContent } from '../../hooks/useSiteContent';
import { useUnsavedChanges } from '../../hooks/useUnsavedChanges';
import type { SiteContentDocument } from '../../types/siteContent';
import { Checkbox } from '../../components/Checkbox';
import { Icon } from '../../components/Icon';
import { Portrait } from '../../components/CommunitySections';
import { LoadingState } from '../../components/LoadingState';
import { ErrorState } from '../../components/ErrorState';
import './adminShared.css';

export function AdminSiteContentPage() {
  const query = useAdminSiteContent();
  const save = useSaveSiteContent();
  const [draft, setDraft] = useState<SiteContentDocument | null>(null);
  const [tab, setTab] = useState('Contact & socials');
  useEffect(() => { if (query.data) setDraft(query.data); }, [query.data]);
  const dirty = !!draft && JSON.stringify(draft) !== JSON.stringify(query.data);
  useUnsavedChanges(dirty);
  if (query.isLoading) return <LoadingState label="Opening site content…" />;
  if (query.isError || !draft) return <ErrorState message="We couldn’t load site content." onRetry={() => query.refetch()} />;
  const content = draft.content;
  const update = (change: Partial<typeof content>) => setDraft({ ...draft, content: { ...content, ...change } });
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate(draft); };
  return <div className="container admin-page"><div className="admin-page__header"><div><span className="eyebrow">MAKE IT YOURS</span><h1>Site content</h1><p className="text-muted">Your people, their stories, and the places learners can find you.</p></div><a href="/about" target="_blank" rel="noopener noreferrer" className="btn btn-secondary">View website <Icon name="diagonal" size={16} /></a></div>
    <div className="content-tabs" role="tablist" aria-label="Content sections">{['Contact & socials', 'Testimonials', 'Team & instructors'].map(item => <button type="button" key={item} role="tab" id={`tab-${item.split(' ')[0]}`} aria-controls="content-panel" aria-selected={tab === item} onClick={() => setTab(item)}>{item}</button>)}</div>
    <form onSubmit={submit} className="site-content-editor">{save.isError && <div className="form-error" role="alert">Your changes haven’t been saved. Check the notification for details.<button type="button" className="text-link" onClick={() => { if (window.confirm('Reload site content and discard your draft?')) { save.reset(); void query.refetch(); } }}>Reload saved content</button></div>}<div id="content-panel" role="tabpanel" aria-labelledby={`tab-${tab.split(' ')[0]}`}>
      {tab === 'Contact & socials' && <><section className="card content-editor-card"><h2>Let’s stay connected</h2><p className="text-muted">These details power the footer, contact section, and registration confirmation.</p><div className="admin-form-grid"><label className="form-field">Support email<input type="email" maxLength={254} value={content.supportEmail} onChange={event => update({ supportEmail: event.target.value })} placeholder="hello@yourdomain.com" /></label><label className="form-field">WhatsApp number<input inputMode="tel" pattern="[0-9]{7,15}" value={content.whatsappNumber} onChange={event => update({ whatsappNumber: event.target.value })} placeholder="Country code and number, digits only" /><small>Leave blank to hide WhatsApp links.</small></label></div></section>
        <section className="card content-editor-card"><h2>Find us around the web</h2><p className="text-muted">Use the arrows to choose how links appear in the footer.</p>{content.socialLinks.map((item, index) => <div className="content-entry" key={index}><div className="admin-form-grid"><label className="form-field">Platform<input required maxLength={50} value={item.platform} placeholder="Instagram, LinkedIn, YouTube…" onChange={event => update({ socialLinks: content.socialLinks.map((entry, i) => i === index ? { ...entry, platform: event.target.value } : entry) })} /></label><label className="form-field">Profile URL<input type="url" required value={item.url} placeholder="https://…" onChange={event => update({ socialLinks: content.socialLinks.map((entry, i) => i === index ? { ...entry, url: event.target.value } : entry) })} /></label></div><div className="content-entry__actions"><label className="admin-checkbox-field"><Checkbox checked={item.published} onChange={event => update({ socialLinks: content.socialLinks.map((entry, i) => i === index ? { ...entry, published: event.target.checked } : entry) })} />Show in footer</label><button type="button" className="btn btn-secondary" disabled={index === 0} aria-label={`Move ${item.platform || 'social link'} up`} onClick={() => { const items = [...content.socialLinks]; [items[index - 1], items[index]] = [items[index], items[index - 1]]; update({ socialLinks: items }); }}>↑</button><button type="button" className="btn btn-secondary" onClick={() => update({ socialLinks: content.socialLinks.filter((_, i) => i !== index) })}>Remove</button></div></div>)}<button type="button" className="btn btn-secondary" disabled={content.socialLinks.length >= 12} onClick={() => update({ socialLinks: [...content.socialLinks, { platform: '', url: '', published: false }] })}>+ Add social link</button></section></>}
      {tab === 'Testimonials' && <section className="card content-editor-card"><h2>Let learners tell their story</h2><p className="text-muted">Add genuine feedback with the learner’s permission. Published stories appear on Home and About.</p>{!content.testimonials.length && <div className="editor-empty"><Icon name="quote" size={32} /><h3>Your first learner story starts here.</h3><p>Add a quote, a name, and an optional portrait.</p></div>}{content.testimonials.map((item, index) => <div className="content-entry" key={index}><Portrait name={item.name || 'Learner'} src={item.avatarUrl} /><div className="admin-form-grid">{(['name', 'role', 'avatarUrl'] as const).map(field => <label className="form-field" key={field}>{field === 'avatarUrl' ? 'Portrait URL (optional)' : field === 'role' ? 'Course / role' : 'Learner name'}<input required={field === 'name'} type={field === 'avatarUrl' ? 'url' : 'text'} value={item[field]} onChange={event => update({ testimonials: content.testimonials.map((entry, i) => i === index ? { ...entry, [field]: event.target.value } : entry) })} /></label>)}<label className="form-field form-field--full">Their words<textarea required maxLength={1500} rows={4} value={item.quote} onChange={event => update({ testimonials: content.testimonials.map((entry, i) => i === index ? { ...entry, quote: event.target.value } : entry) })} /></label></div><div className="content-entry__actions"><label className="admin-checkbox-field"><Checkbox checked={item.published} onChange={event => update({ testimonials: content.testimonials.map((entry, i) => i === index ? { ...entry, published: event.target.checked } : entry) })} />Publish this story</label><button type="button" className="btn btn-secondary" onClick={() => update({ testimonials: content.testimonials.filter((_, i) => i !== index) })}>Remove</button></div></div>)}<button type="button" className="btn btn-secondary" disabled={content.testimonials.length >= 30} onClick={() => update({ testimonials: [...content.testimonials, { name: '', role: '', quote: '', avatarUrl: '', published: false }] })}>+ Add testimonial</button></section>}
      {tab === 'Team & instructors' && <section className="card content-editor-card"><h2>The people behind the progress</h2><p className="text-muted">Published profiles appear under Meet the team. Instructors also appear on Home. Course-specific instructor details remain in the course editor.</p>{!content.team.length && <div className="editor-empty"><Icon name="users" size={32} /><h3>Introduce your people.</h3><p>Give learners a face and a story to connect with.</p></div>}{content.team.map((item, index) => <div className="content-entry" key={index}><Portrait name={item.name || 'Team'} src={item.avatarUrl} /><div className="admin-form-grid">{(['name', 'role', 'avatarUrl', 'profileUrl'] as const).map(field => <label className="form-field" key={field}>{({ name: 'Full name', role: 'Role / expertise', avatarUrl: 'Portrait URL (optional)', profileUrl: 'Profile URL (optional)' })[field]}<input required={field === 'name' || field === 'role'} type={field.endsWith('Url') ? 'url' : 'text'} value={item[field]} onChange={event => update({ team: content.team.map((entry, i) => i === index ? { ...entry, [field]: event.target.value } : entry) })} /></label>)}<label className="form-field form-field--full">About this person<textarea required maxLength={2500} rows={4} value={item.bio} onChange={event => update({ team: content.team.map((entry, i) => i === index ? { ...entry, bio: event.target.value } : entry) })} /></label></div><div className="content-entry__actions">{(['instructor', 'published'] as const).map(field => <label key={field} className="admin-checkbox-field"><Checkbox checked={item[field]} onChange={event => update({ team: content.team.map((entry, i) => i === index ? { ...entry, [field]: event.target.checked } : entry) })} />{field === 'instructor' ? 'Course instructor' : 'Publish profile'}</label>)}<button type="button" className="btn btn-secondary" onClick={() => update({ team: content.team.filter((_, i) => i !== index) })}>Remove</button></div></div>)}<button type="button" className="btn btn-secondary" disabled={content.team.length >= 30} onClick={() => update({ team: [...content.team, { name: '', role: '', bio: '', avatarUrl: '', profileUrl: '', instructor: false, published: false }] })}>+ Add team member</button></section>}
    </div><div className="editor-save-bar"><span><span className={`save-dot ${dirty ? 'is-dirty' : ''}`} />{dirty ? 'Unsaved changes' : 'Everything is up to date'}</span><div className="admin-actions-row"><button type="button" className="btn btn-secondary" disabled={!dirty || save.isPending} onClick={() => { if (window.confirm('Discard your unsaved changes?')) setDraft(query.data!); }}>Discard</button><button type="submit" className="btn btn-primary" disabled={!dirty || save.isPending}>{save.isPending ? 'Saving…' : 'Save site content'}<Icon name="check" size={17} /></button></div></div></form></div>;
}
