import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { apiClient } from "../../api/client";
import { Select } from "../../components/Select";
import { LoadingState } from "../../components/LoadingState";
import { ErrorState } from "../../components/ErrorState";
import { sanitizeRichText } from "../../utils/richText";
import type { StudentClassSession } from "../../types/student";
import "./adminShared.css";
import "./learningInsights.css";

type CourseMetrics={id:number;title:string;learners:number;recent:number;overdue:number;pending:number;attempts:number;passed:number};
type Analytics={courses:CourseMetrics[];courseOptions:{id:number;title:string}[];cohortOptions:{id:number;name:string;course_id:number}[]};
export function AdminAnalyticsPage(){
 const [course,setCourse]=useState("");const [cohort,setCohort]=useState("");
 const q=useQuery({queryKey:["admin","learning-analytics",course,cohort],queryFn:async()=>(await apiClient.get<Analytics>("/api/admin/learning/analytics",{params:{courseId:course||undefined,cohortId:cohort||undefined}})).data});
 const rows=q.data?.courses??[];
 const sum=(key:keyof Omit<CourseMetrics,"id"|"title">)=>rows.reduce((n,r)=>n+Number(r[key]),0);
 return <div className="container admin-page insights"><header className="admin-page__header"><div><span className="eyebrow">LEARNING INTELLIGENCE</span><h1>A clearer picture of progress.</h1><p className="text-muted">Find where learners need support and keep feedback moving.</p></div><Link className="btn btn-primary" to="/admin/grading">Open grading queue</Link></header>
 <div className="insights-filters"><label>Course<Select value={course} onChange={e=>{setCourse(e.target.value);setCohort("");}}><option value="">All courses</option>{q.data?.courseOptions.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select></label><label>Cohort<Select value={cohort} onChange={e=>setCohort(e.target.value)}><option value="">All cohorts</option>{q.data?.cohortOptions.filter(c=>!course||String(c.course_id)===course).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label><button className="btn btn-ghost" disabled={!course&&!cohort} onClick={()=>{setCourse("");setCohort("");}}>Reset filters</button></div>
 {q.isLoading?<LoadingState/>:q.isError?<ErrorState onRetry={()=>q.refetch()}/>:<><div className="insights-stats">{[["Active course enrollments",sum("learners"),"Each learner counted once per course"],["Recently learning",sum("recent"),"Recorded activity in the last 14 days"],["Overdue tasks",sum("overdue"),"Missing work or resubmission required"],["Awaiting feedback",sum("pending"),"Submitted or under review"]].map(([label,value,detail])=><article key={label} className="insights-stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
 <section className="insights-section"><div><span className="eyebrow">COURSE HEALTH</span><h2>Turn insight into support.</h2><p className="text-muted">Activity includes lesson completions, quiz attempts, assignment submissions and saved drafts. It does not measure logins or time spent.</p></div><div className="insights-courses">{rows.map(c=><article className="insights-course" key={c.id}><div><h3>{c.title}</h3><span className="text-muted">{c.learners} enrolled · {c.learners-c.recent} with no recent recorded activity</span></div><div><div className="insights-meter-label"><span>Recent activity</span><strong>{c.learners?Math.round(c.recent/c.learners*100):0}%</strong></div><meter min={0} max={Math.max(1,c.learners)} value={c.recent} aria-label={`${c.title}: recently active learners`}/></div><dl><div><dt>Overdue tasks</dt><dd>{c.overdue}</dd></div><div><dt>Grading backlog</dt><dd>{c.pending}</dd></div><div><dt>Quiz pass rate</dt><dd>{c.attempts?`${Math.round(c.passed/c.attempts*100)}%`:"—"}<small>{c.attempts} submitted attempts</small></dd></div></dl><Link className="btn btn-secondary" to={`/admin/courses/${c.id}/preview`}>Preview learning content ↗</Link></article>)}</div>{!rows.length&&<p>No courses match these filters.</p>}</section><p className="text-muted">Only active enrollments with non-cancelled registrations are included. Cohort filters respect lesson visibility. Quiz rates count attempts, including retries.</p></>}
 </div>;
}

type Outline={title:string;cohorts:{id:number;name:string}[];lessons:{id:number;title:string;module:string;cohortId:number|null}[]};
type Preview={lesson:StudentClassSession;passingPercentage:number|null;questions:{id:number;text:string;points:number;options:{position:number;text:string}[]}[];criteria:{id:string;label:string;maxPoints:number;description:string}[]};
const Rich=({value}:{value:string|null|undefined})=>value?<div className="rich-content" dangerouslySetInnerHTML={{__html:sanitizeRichText(value)}}/>:null;
function SafeLink({url,children}:{url:string|null;children:React.ReactNode}){if(!url||!/^https?:\/\//i.test(url))return null;return <a className="btn btn-secondary" href={url} target="_blank" rel="noopener noreferrer">{children} ↗</a>;}
function LessonPreview({id}:{id:number}){
 const [answers,setAnswers]=useState<Record<number,number>>({});
 const q=useQuery({queryKey:["admin","lesson-preview",id],queryFn:async()=>(await apiClient.get<Preview>(`/api/admin/learning/classes/${id}/preview`)).data});
 if(q.isLoading)return <LoadingState/>;if(q.isError)return <ErrorState onRetry={()=>q.refetch()}/>;if(!q.data)return null;
 const {lesson:s,questions,criteria}=q.data;const a=s.assignment;
 return <><header className="preview-hero"><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>{s.title}</h2><Rich value={s.objectives}/>{s.scheduledAt&&<p>{new Date(s.scheduledAt).toLocaleString()}</p>}<div className="admin-actions-row"><SafeLink url={s.meetingLink}>Meeting link</SafeLink><SafeLink url={s.recordingUrl}>Watch recording</SafeLink></div></header>
 {s.sections.map((section,i)=><section className="preview-section" key={i}><span className="eyebrow">LESSON {String(i+1).padStart(2,"0")}</span><h3>{section.title}</h3><Rich value={section.body}/></section>)}
 {!!s.materials.length&&<section className="preview-section"><h3>Your resources</h3>{s.materials.map(m=><div className="preview-resource" key={m.id}><strong>{m.title}</strong><Rich value={m.description}/><SafeLink url={m.fileUrl}>{m.fileName||"Open material"}</SafeLink></div>)}</section>}
 {!!questions.length&&<section className="preview-section"><span className="eyebrow">KNOWLEDGE CHECK</span><h3>Put your learning into practice.</h3><p>{questions.length} questions · {q.data.passingPercentage}% to pass</p><p className="text-muted">Try selecting answers. Preview selections stay on this page and are not graded or saved.</p>{questions.map((question,i)=><fieldset className="preview-question" key={question.id}><legend>{i+1}. {question.text} <small>({question.points} points)</small></legend>{question.options.map(option=><button type="button" className="preview-option" key={option.position} aria-pressed={answers[question.id]===option.position} onClick={()=>setAnswers({...answers,[question.id]:option.position})}><span aria-hidden="true">{answers[question.id]===option.position?"●":"○"}</span>{option.text}</button>)}</fieldset>)}<button className="btn btn-ghost" onClick={()=>setAnswers({})}>Reset selections</button></section>}
 {a&&<section className="preview-section"><span className="eyebrow">MAKE IT YOUR OWN</span><h3>{a.title}</h3><p>{a.maxScore} points{a.dueAt?` · Due ${new Date(a.dueAt).toLocaleString()}`:" · No deadline set"}</p>{[["Learning objective",a.learningObjective],["Instructions",a.instructions],["Tasks",a.tasks],["Submission requirements",a.submissionRequirements],["Rubric",a.rubric]].map(([label,value])=>value?<div key={label}><h4>{label}</h4><Rich value={value}/></div>:null)}{!!criteria.length&&<><h4>How your work is assessed</h4>{criteria.map(c=><div className="preview-resource" key={c.id}><strong>{c.label} · {c.maxPoints} points</strong><p>{c.description}</p></div>)}</>}<p className="text-muted">Accepted attachments: {a.allowedAttachmentTypes||"See submission requirements"}. Submissions are disabled in preview.</p></section>}
 {!s.sections.length&&!a&&!questions.length&&<section className="preview-section"><p>This lesson has no reading sections or assessments yet.</p></section>}</>;
}
export function AdminLearningPreviewPage(){
 const {id}=useParams();const [selected,setSelected]=useState("");const [cohort,setCohort]=useState("");const [narrow,setNarrow]=useState(false);
 const q=useQuery({queryKey:["admin","course-preview",id],queryFn:async()=>(await apiClient.get<Outline>(`/api/admin/learning/courses/${id}/preview`)).data});
 const lessons=q.data?.lessons.filter(s=>!cohort||s.cohortId===null||String(s.cohortId)===cohort)??[];
 const active=lessons.find(s=>String(s.id)===selected)??lessons[0];
 const cohorts=[...new Set(q.data?.lessons.flatMap(s=>s.cohortId===null?[]:[s.cohortId])??[])];
 return <div className="container admin-page insights"><header className="admin-page__header"><div><span className="eyebrow">STUDENT CONTENT PREVIEW</span><h1>{q.data?.title??"Learning preview"}</h1><p className="text-muted">Read-only content review. No enrollment, progress, grades or attempts are created.</p></div><Link className="btn btn-secondary" to={`/admin/courses/${id}/outline`}>Back to course editor</Link></header>
 {q.isLoading?<LoadingState/>:q.isError?<ErrorState onRetry={()=>q.refetch()}/>:<><div className="insights-filters"><label>Lesson visibility<Select value={cohort} onChange={e=>{setCohort(e.target.value);setSelected("");}}><option value="">All lessons (admin)</option>{cohorts.map(c=><option value={c} key={c}>{q.data?.cohorts?.find(h=>h.id===c)?.name??`Cohort ${c}`} + shared lessons</option>)}</Select></label><label>Lesson<Select value={active?.id??""} onChange={e=>setSelected(e.target.value)}>{lessons.map(s=><option value={s.id} key={s.id}>{s.module} · {s.title}</option>)}</Select></label><button className="btn btn-secondary" aria-pressed={narrow} onClick={()=>setNarrow(!narrow)}>{narrow?"Use full width":"Use narrow width"}</button></div><p className="text-muted">{cohort?"Showing shared lessons and this cohort’s lessons.":"All cohort lessons are visible to admins here; students only see their enrolled cohort."} Narrow width checks content wrapping; it is not a device emulator.</p>{active?<div className={`preview-canvas${narrow?" preview-canvas--narrow":""}`}><LessonPreview key={active.id} id={active.id}/></div>:<section className="preview-section"><h2>No lessons yet</h2><p>Add a class session in the course editor to preview it here.</p></section>}</>}
 </div>;
}
