import { useParams, Link } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiClient } from "../../api/client";
import { LoadingState } from "../../components/LoadingState";
import { ErrorState } from "../../components/ErrorState";
import "./adminShared.css";
type Detail={id:number;name:string;email:string;studentCode:string;suspended:boolean;enrollments:{id:number;courseId:number;courseTitle:string;cohortName:string;active:boolean;registrationStatus:string;progress:{overallPercentage:number;classesCompleted:number;classesTotal:number;quizzesPassed:number;quizzesTotal:number;assignmentsReviewed:number;assignmentsTotal:number}|null}[]};
export function AdminStudentDetailPage(){const {studentId}=useParams();const cache=useQueryClient();const key=["admin","student-detail",studentId];
 const q=useQuery({queryKey:key,queryFn:async()=>(await apiClient.get<Detail>(`/api/admin/students/${studentId}`)).data});
 const action=useMutation({meta:{notify:true},mutationFn:async({path,enabled}:{path:string;enabled?:boolean})=>enabled===undefined?apiClient.post(path):apiClient.put(path,{enabled}),onSuccess:()=>cache.invalidateQueries({queryKey:key})});
 if(q.isLoading)return <LoadingState/>;if(!q.data)return <ErrorState message="Could not load this student." onRetry={()=>q.refetch()}/>;const s=q.data;
 return <div className="container admin-page"><div className="admin-page__header"><div><span className="eyebrow">STUDENT PROFILE</span><h1>{s.name}</h1><p>{s.studentCode} · {s.email}</p></div><Link className="btn btn-secondary" to="/admin/students">All students</Link></div>
 <div className="card admin-form-panel"><h2>Account access</h2><p>{s.suspended?"Sign-in is suspended.":"Sign-in is enabled."}</p><div className="admin-actions-row"><button className="btn btn-secondary" disabled={action.isPending||s.suspended} onClick={()=>action.mutate({path:`/api/admin/students/${s.id}/recovery`})}>Send password / invitation link</button><button className="btn btn-secondary" disabled={action.isPending} onClick={()=>action.mutate({path:`/api/admin/students/${s.id}/access`,enabled:s.suspended})}>{s.suspended?"Restore sign-in":"Suspend sign-in"}</button></div></div>
 {s.enrollments.map(e=><section className="card admin-form-panel" key={e.id}><h2>{e.courseTitle}</h2><p>{e.cohortName} · {e.registrationStatus.toLowerCase()} · {e.active?"Access enabled":"Access revoked"}</p>{e.progress&&<><p><strong>{e.progress.overallPercentage}% progress</strong></p><div className="admin-detail-grid"><p>Lessons: {e.progress.classesCompleted}/{e.progress.classesTotal}</p><p>Quizzes passed: {e.progress.quizzesPassed}/{e.progress.quizzesTotal}</p><p>Assignments reviewed: {e.progress.assignmentsReviewed}/{e.progress.assignmentsTotal}</p></div></>}
 <button className="btn btn-secondary" disabled={action.isPending||e.registrationStatus==="CANCELLED"} onClick={()=>action.mutate({path:`/api/admin/students/${s.id}/enrollments/${e.id}/access`,enabled:!e.active})}>{e.active?"Revoke course access":"Restore course access"}</button>{e.registrationStatus==="CANCELLED"&&<p className="text-muted">Restore the registration before enabling access.</p>}</section>)}</div>;}
